CREATE TABLE public.logs (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	date_time timestamptz NOT NULL,
	ticker varchar NOT NULL,
	balance int4 NOT NULL,
	interval varchar NOT NULL,
	days varchar NOT NULL,
	CONSTRAINT logs_pk PRIMARY KEY (id)
);