CREATE TABLE public.logs (
	id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	indicator_name varchar NOT NULL,
	indicator_data jsonb DEFAULT '{}'::jsonb NOT NULL,
	buy_signals jsonb DEFAULT '[]'::jsonb NOT NULL,
	sell_signals jsonb DEFAULT '[]'::jsonb NOT NULL,
	CONSTRAINT logs_pk PRIMARY KEY (id)
);