CREATE TABLE public.migrations (
    id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar NOT NULL,
    date timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT migrations_pk PRIMARY KEY (id)
);